# -*- coding: utf-8 -*-
"""DesafioFinalNumpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDc7-hthkm5PV4s4xUfE2Ov9mw1oY-7P
"""

import numpy as np

''' Ejercicio 1 '''
A = np.array([[-2,-2,4],[-4,1,2],[2,2,5]])
print(A)

v1=np.array([[1],[1],[1]])
print(v1)


v2=np.array([[1],[2],[3]])
print(v2)

'''Ejercicio 2'''
##Norma I0 
##La norma I0 de una matriz es la cantidad de elementos no nulos en la matriz, es decir, la cantidad de elementos distintos de cero
n0_A=np.count_nonzero(A,1)
print("Cantidad de elementos distitnos de cero en la matriz:",n0_A)


##Norma I1
##La norma I1 de una matriz se define como la suma de los valores absolutos de los elementos de la matriz por columnas
n1_A=np.sum(np.abs(A),0)
print("La suma de los valores absolutos de la matriz A por columnas es: ",n1_A)


##Norma I2
##La norma I2 de una matriz se define como la raíz cuadrada de la suma de los cuadrados de todos los elementos de la fila de la matriz
n2_A=np.sqrt(np.sum(A**2,1))
print("La raíz cuadrada de la suma de los cuadrados de todos los elementos por fila de la matriz es", n2_A)


##Norma Iinf
##La norma I∞ de una matriz es el máximo valor absoluto de entre todas las sumas de valores absolutos por filas de la matriz. 

ninf_A = np.max(np.sum(np.abs(A),1))
print("El máximo valor absoluto de entre todas las sumas de valores absolutos por filas de la matriz A es",ninf_A)

'''Ejercicio 3'''

##Norma I2 de cada vector está contenida en n2_A
np.sort(n2_A).reshape(3,1)

'''Ejercicio 4'''

def funct(matriz):
  media=np.mean(matriz,0)
  desv=np.std(matriz,0)
  resultado=(matriz-media)/desv
  return resultado

funct(A)







